### ISSUE TITLE
Can't install on Ruby 2.5 environment

### ISSUE THREAD

**Issue by exoego** [mzp/SlackStack#4]
Hi there.
Thanks for creating this amazing software.

I tried build the binary on Ruby 2.5 on Windows and it failed on `bundle install`.
It would be helpful if `SlackStack` support Ruby 2.5 since 2.5 introduced some performance tweaks ([Ruby 2.5.0 release notes](https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/))

# Ruby version
```
$ ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
```

# How to reproduce

1. Install Ruby+Devkit 2.5.3.-1 (x64) binay grabbed from https://rubyinstaller.org/downloads/
2. `gem install bundle`.
3. `git clone https://github.com/mzp/SlackStack.git`
4. `cd SlackStack`
5. `bundle install` then error message shown

# Error message
```
Fetching unf_ext 0.0.7.4 (x64-mingw32)
Installing unf_ext 0.0.7.4 (x64-mingw32)
Gem::RuntimeRequirementNotMetError: unf_ext requires Ruby version < 2.5, >= 2.0.
The current ruby version is 2.5.0.
An error occurred while installing unf_ext (0.0.7.4), and Bundler
cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.4' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  gym was resolved to 2.0.0, which depends on
    fastlane was resolved to 2.28.7, which depends on
      faraday-cookie_jar was resolved to 0.0.6, which depends on
        http-cookie was resolved to 1.0.3, which depends on
          domain_name was resolved to 0.5.20170404, which depends on
            unf was resolved to 0.1.4, which depends on
              unf_ext
```

**Comment by mzp** [comment]
SlackStack only runs on macOS. It use Ruby to install dependencies library. 

So, it is not important to support Ruby on Windows.

**Comment by exoego** [comment]
Oops 😓 
I did not notice this is only for Mac.
Sorry for silly issue.
